## Travis CI Integration

language: c

install:
  - sudo apt-get install mono-devel mono-gmcs nunit-console
script:
  - xbuild MiniMessagePack.sln
  - nunit-console MiniMessagePackTest/bin/Debug/MiniMessagePackTest.dll
